# see https://cwiki.apache.org/confluence/display/INFRA/git+-+.asf.yaml+features#git.asf.yamlfeatures-GitHubsettings

github:
  description: "Scripts to manage IBM cloud instances running Jenkins CI workers"
  homepage: https://couchdb.apache.org/

notifications:
  commits: commits@couchdb.apache.org
  issues: notifications@couchdb.apache.org
  pullrequests: notifications@couchdb.apache.org
  # This would send new/closed PR notifications to dev@
  #pullrequests_status: dev@couchdb.apache.org
  # This would send individual PR comments/reviews to notifications@
  #pullrequests_comment: notifications@couchdb.apache.org
