- name: Install Docker gpg key for Apt
  become: yes
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Setup Docker Apt repository
  become: yes
  apt_repository:
    repo: deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
    filename: docker
    state: present

- name: Install Docker Packages
  become: yes
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - containerd.io
      - docker-ce
      - docker-ce-cli

- name: Install multi-architecture support for Docker
  become: yes
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - binfmt-support
      - qemu
      - qemu-user-static

- name: Install Java 8
  become: yes
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - openjdk-8-jre-headless

- name: Add group jenkins
  become: yes
  group:
    name: jenkins
    gid: 910

- name: Add user jenkins
  become: yes
  user:
    name: jenkins
    uid: 910
    groups:
      - jenkins
      - docker
    state: present
    shell: /bin/bash

- name: Add Apache Infra ssh key
  become: yes
  authorized_key:
    user: jenkins
    key: ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAIEAtxkcKDiPh1OaVzaVdc80daKq2sRy8aAgt8u2uEcLClzMrnv/g19db7XVggfT4+HPCqcbFbO3mtVnUnWWtuSEpDjqriWnEcSj2G1P53zsdKEu9qCGLmEFMgwcq8b5plv78PRdAQn09WCBI1QrNMypjxgCKhNNn45WqV4AD8Jp7/8=

- name: Install kill-old-docker.sh
  become: yes
  copy:
    src: kill-old-docker.sh
    dest: /usr/local/bin/kill-old-docker.sh
    mode: 0755

- name: Add kill-old-docker.sh cron entry
  become: yes
  cron:
    name: Kill old docker containers
    hour: '19'
    job: /usr/local/bin/kill-old-docker.sh

- name: Add docker prune cron entry
  become: yes
  cron:
    name: Docker prune
    hour: '19'
    job: /usr/bin/docker system prune -a -f --filter "until=72h"
