- name: Configure TCP Keep-Alive
  copy:
    src: 50-ci-agent.sysctl.conf
    dest: /etc/sysctl.d/50-ci-agent.conf
    mode: 0644
  register: ciagentsysctl

- name: Load TCP Keep-Alive configuration
  shell: /sbin/sysctl --load /etc/sysctl.d/50-ci-agent.conf
  when: ciagentsysctl.changed

- name: Install Java 8
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - openjdk-8-jre-headless

- name: Add group jenkins
  group:
    name: jenkins
    gid: 910

- name: Add user jenkins
  user:
    name: jenkins
    uid: 910
    groups:
      - jenkins
    state: present
    shell: /bin/bash

- name: Setup Docker on x86_64 hosts
  include_tasks: docker.yml
  when:
    - ansible_facts['architecture'] == 'x86_64'

- name: Create Jenkins runit service directory
  file:
    path: /etc/sv/jenkins
    state: directory

- name: Create Jenkins runit log directory
  file:
    path: /etc/sv/jenkins/log/main
    state: directory

- name : Create Jenkins runit run script
  template:
    src: runit-main.j2
    dest: /etc/sv/jenkins/run
    mode: 0755

- name: Create Jenkins runit logs run script
  copy:
    src: runit-logs
    dest: /etc/sv/jenkins/log/run
    mode: 0755

- name: Enable Jenkins runit service
  file:
    src: /etc/sv/jenkins
    dest: /etc/service/jenkins
    state: link


