- name: Allow CouchDB Infra access
  authorized_key:
    user: root
    state: present
    key: "{{ item }}"
  with_items:
    - https://github.com/davisp.keys
    - https://github.com/wohali.keys

- name: Install basic ubiquitous packages
  become: yes
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  vars:
    packages:
      - apt-transport-https
      - atop
      - ca-certificates
      - curl
      - git
      - gnupg2
      - iftop
      - iperf3
      - mtr-tiny
      - nload
      - ntp
      - python3
      - runit
      - runit-systemd
      - screen
      - software-properties-common
      - strace
      - sudo
      - tcpdump
      - tmux
      - vim
      - wget
